### PR TITLE
fix(blog): Restrict pages to admin-only without plugin

### LINKED ISSUE #11: Getting a blank screen on several blog pages
admin_blog plugin duplicates a lot of blog rendering logic using the elgg:blog library and functions, many of which were removed in 2.0...

### PR DESCRIPTION
**Pull request by ewinslow**
The admin_blog plugin was trying to restrict blogs at too high of a level.
This prevents blog submission at the permissions level (very low level)
so there isn't nearly as much code to maintain.

Fixes #11

### CODE REVIEW

**Comment by ewinslow** [comment]
The admin_blog plugin also did extra work to remove UI elements that didn't make sense. IMO this should not be necessary. Elgg should be doing a lot of that automatically.

**Comment by mrclay** [comment]
Looks right

**Comment by ewinslow** [comment]
I think this is enough to re-enable the blog.

We'll still want to fix the issues where we show misleading UI, but getting blog back up is a priority ATM

**Comment by mrclay** [comment]
go for it

**Comment by ewinslow** [comment]
thnx

**Pull request merged**
